gnome-terminal -x bash -c "./run-sh/run-01.sh;exec bash;"
gnome-terminal -x bash -c "./run-sh/run-02.sh;exec bash;"
gnome-terminal -x bash -c "./run-sh/run-03.sh;exec bash;"
gnome-terminal -x bash -c "./run-sh/run-04.sh;exec bash;"
gnome-terminal -x bash -c "./run-sh/run-05.sh;exec bash;"
gnome-terminal -x bash -c "./run-sh/run-06.sh;exec bash;"
gnome-terminal -x bash -c "./run-sh/run-07.sh;exec bash;"
gnome-terminal -x bash -c "./run-sh/run-08.sh;exec bash;"
gnome-terminal -x bash -c "./run-sh/run-09.sh;exec bash;"
gnome-terminal -x bash -c "./run-sh/run-10.sh;exec bash;"
gnome-terminal -x bash -c "source /etc/profile;~/anaconda3/envs/torch1.6/bin/python3 /data/jcliu/RE-AFL/server_thread.py --world_size 10 --dataset_type FashionMNIST --alpha 0.1 --rank 0;exec bash;"
